#########################################################
#         :::::::::       :::::::::      :::::::::::
#        :+:    :+:      :+:    :+:         :+:
#       +:+    +:+      +:+    +:+         +:+
#      +#++:++#:       +#++:++#+          +#+
#     +#+    +#+      +#+    +#+         +#+
#    #+#    #+#      #+#    #+#     #+# #+#
#   ###    ###      #########       #####
########################################################

rbj:
  NoPermissions: "§4[§c!§4] §3You dont have the Permission to do that!" # rbj.reload
  Prefix: "§8« §3RBJ §8» "

Join:
  Message: "§3[§a+§3] §b%player_displayname% §7say hey to everyone!"
  Sound: true
  PrivateMessage: "§d————————»\n §3Hey, %player_displayname%!\n §3You can do §6/help §3to get help!\n§d«————————"

Leave:
  Message: "§3[§4-§3] §b%player_displayname% §7say bye to everyone!"

Commands:
  Reload: "§3Reloaded, fast like Flash!"

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
#| By lultwo
#|  © Copyright 2023 lultwo
#|
#|  Tips:
#| You can use BLANK Strings "" to disable a Message
#| You can use PlaceholderAPI to create a Message that looks better
#| You can use "\n" to go next line, like my Template in "PrivateMessage"
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\