#########################################################
#         :::::::::       :::::::::      :::::::::::
#        :+:    :+:      :+:    :+:         :+:
#       +:+    +:+      +:+    +:+         +:+
#      +#++:++#:       +#++:++#+          +#+
#     +#+    +#+      +#+    +#+         +#+
#    #+#    #+#      #+#    #+#     #+# #+#
#   ###    ###      #########       #####
########################################################

#      /||\  Here you can edit the NoPerms Message when a Player without Reload Permissions try
#            to reload the Plugin  /||\
rbj:
  NoPermissions: "§4[§c!§4] §3You dont have the Permission to do that!" # rbj.reload
  Prefix: "§8« §3RBJ §8» "

#      /||\  Here you can edit the GLOBAL Message when a Player join  /||\
JoinMessage: "§3[§a+§3] §b%player_displayname% §7say hey to everyone!"
#      /||\  Here you can edit the GLOBAL Message when a Player leave  /||\
LeaveMessage: "§3[§4-§3] §b%player_displayname% §7say bye to everyone!"

#      /||\  Here you can edit the PRIVATE Message when a Player join  /||\
PrivateMessage: "§d————————»\n §3Hey, %player_displayname%!\n §3You can do §6/help §3to get help!\n§d«————————"

#      /||\ Here you can set the Message that will send when you use a Command  /||\
Commands:
  Reload: "§3Reloaded, fast like Flash!"

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
#| By lultwo
#|  © Copyright 2023 lultwo
#|
#|  Tips:
#| You can use BLANK Strings "" to disable a Message
#| You can use PlaceholderAPI to create a Message that looks better
#| You can use "\n" to go next line, like my Template in "PrivateMessage"
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\